# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

development:
  # <<: *default
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

test:
  # <<: *default
    adapter: postgresql
    database: my_database_development
    pool: 5
    timeout: 5000

production:
  # <<: *default
    adapter: postgresql
    database: my_database_development
    pool: 5
    timeout: 5000
